# This file has been generated by node2nix 1.4.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "node-zstandard-1.2.4" = {
      name = "node-zstandard";
      packageName = "node-zstandard";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-zstandard/-/node-zstandard-1.2.4.tgz";
        sha1 = "44f62eb7cb626b948ec79dd2327d3e594ada2f06";
      };
    };
  };
  args = {
    name = "Chlorine";
    packageName = "Chlorine";
    version = "1.0.5";
    src = ./.;
    dependencies = [
      sources."node-zstandard-1.2.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Replay viewer for Halite 2";
    };
    production = true;
    postInstall = ''
      patchelf \
              --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" \
              $out/lib/node_modules/Chlorine/node_modules/node-zstandard/bin/zstd.linux64

      mkdir -p $out/bin
      cp chlorine.sh $out/bin/chlorine
      '';

  };
in
{
  package = nodeEnv.buildNodePackage args;
}
